// classes/parte-7-renderizado-y-fullstack/099-la-cascada-de-peticiones/implementaciones/remix/app/routes/cascada.jsx
import { useLoaderData } from "@remix-run/react";

import Panel from "../Panel.jsx";
import { enCascada } from "../fuente.js";

/** Tres `await` seguidos dentro del `loader`. Que la carga esté junto a la ruta
 *  —clase 097— no impide escribir una cascada: solo la mueve al servidor, donde
 *  al menos la red es rápida. */
export async function loader() {
  return { datos: await enCascada() };
}

export default function Cascada() {
  const { datos } = useLoaderData();
  return <Panel como="cascada" datos={datos} />;
}

// classes/parte-7-renderizado-y-fullstack/099-la-cascada-de-peticiones/implementaciones/nuxt/pages/cascada.vue
<script setup lang="ts">
import { enCascada } from "../fuente.js";

// Tres `await` seguidos dentro del cargador. Da igual que se envuelvan en
// `useAsyncData`: la clave y la deduplicación no arreglan el orden, solo evitan
// pedir dos veces lo mismo.
const { data: datos } = await useAsyncData("cascada", () => enCascada());
</script>

<template>
  <Panel como="cascada" :datos="datos" />
</template>
