// classes/parte-7-renderizado-y-fullstack/093-las-cuatro-estrategias-de-renderizado/implementaciones/remix/app/routes/servidor.jsx
import { useLoaderData } from "@remix-run/react";

import { TAREAS, sello } from "../datos";

/**
 * EL MODELO POR OMISIÓN DE REMIX, Y EL ÚNICO.
 *
 * `loader` corre en el servidor en cada petición. No hay que declarar nada
 * porque no hay alternativa que declarar — y esa ausencia de opciones es lo que
 * Remix ofrece a cambio: una sola forma de hacer las cosas.
 */
export function loader() {
  return { tareas: TAREAS, marca: sello() };
}

export default function Servidor() {
  const { tareas, marca } = useLoaderData();
  return (
    <ul data-estrategia="servidor" data-sello={marca}>
      {tareas.map((t) => (
        <li key={t}>{t}</li>
      ))}
    </ul>
  );
}

// classes/parte-7-renderizado-y-fullstack/093-las-cuatro-estrategias-de-renderizado/implementaciones/nuxt/pages/servidor.vue
<script setup lang="ts">
import { TAREAS, sello } from "../datos";

// Y esta se renderiza en cada petición. El archivo es idéntico al de al lado
// salvo por el atributo `data-estrategia`: lo único que las separa es una línea
// en `nuxt.config.ts`.
const marca = sello();
</script>

<template>
  <ul data-estrategia="servidor" :data-sello="marca">
    <li v-for="tarea in TAREAS" :key="tarea">{{ tarea }}</li>
  </ul>
</template>
