// classes/parte-7-renderizado-y-fullstack/104-elegir-estrategia-por-pantalla/implementaciones/nuxt/pages/panel.vue
<script setup lang="ts">
import { sello, ventasDeHoy } from "../datos";

// LA SEGUNDA PANTALLA. Tampoco lleva marca: la regla dice `prerender: false`, y
// eso es además el valor por omisión.
const ventas = ventasDeHoy();
const marca = sello();
</script>

<template>
  <div>
    <h1>Panel</h1>
    <p data-estrategia="servidor" :data-sello="marca">
      {{ ventas.pedidos }} pedidos, {{ ventas.importe }} euros
    </p>
  </div>
</template>

// classes/parte-7-renderizado-y-fullstack/104-elegir-estrategia-por-pantalla/implementaciones/remix/app/routes/panel.jsx
import { useLoaderData } from "@remix-run/react";

import { sello, ventasDeHoy } from "../datos.js";

/** LA SEGUNDA PANTALLA, que en Remix no necesita declarar nada porque no hay
 *  alternativa que declarar. Es el modelo por omisión y el único. */
export function loader() {
  return { ventas: ventasDeHoy(), marca: sello() };
}

export default function Panel() {
  const { ventas, marca } = useLoaderData();
  return (
    <>
      <h1>Panel</h1>
      {/* Una sola expresión y no tres: React separa los trozos de texto con
          comentarios en el HTML, y entonces «12 pedidos» deja de estar seguido. */}
      <p data-estrategia="servidor" data-sello={marca}>
        {`${ventas.pedidos} pedidos, ${ventas.importe} euros`}
      </p>
    </>
  );
}
