// classes/parte-7-renderizado-y-fullstack/099-la-cascada-de-peticiones/implementaciones/nuxt/components/Panel.vue
<script setup lang="ts">
// La misma pantalla para las dos rutas.
defineProps<{ como: string; datos: any }>();
</script>

<template>
  <main :data-como="como">
    <h1>Hola, {{ datos.usuario.nombre }}</h1>
    <p :data-pedidos="datos.pedidos.length">{{ datos.pedidos.length }} pedidos</p>
    <ul>
      <li v-for="aviso in datos.avisos" :key="aviso">{{ aviso }}</li>
    </ul>
  </main>
</template>

// classes/parte-7-renderizado-y-fullstack/099-la-cascada-de-peticiones/implementaciones/remix/app/Panel.jsx
/** La misma pantalla para las dos rutas. Es importante que sea la misma: si el
 *  marcado cambiara, la comparación mediría el marcado. */
export default function Panel({ como, datos }) {
  return (
    <main data-como={como}>
      <h1>Hola, {datos.usuario.nombre}</h1>
      <p data-pedidos={datos.pedidos.length}>{datos.pedidos.length} pedidos</p>
      <ul>
        {datos.avisos.map((aviso) => (
          <li key={aviso}>{aviso}</li>
        ))}
      </ul>
    </main>
  );
}
