// classes/parte-7-renderizado-y-fullstack/093-las-cuatro-estrategias-de-renderizado/implementaciones/nuxt/pages/cliente.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

// LA TERCERA ESTRATEGIA.
//
// `onMounted` no corre en el servidor —clase 087— así que el HTML sale con la
// lista vacía y los datos llegan cuando el navegador ejecuta el JavaScript.
//
// En Nuxt esto es una decisión deliberada: `useFetch` o `useAsyncData` traerían
// los datos ANTES de renderizar y llegarían en el HTML. Pedirlos en `onMounted`
// es elegir explícitamente la estrategia de cliente.
const tareas = ref<string[]>([]);
const pendiente = ref("si");

onMounted(async () => {
  const respuesta = await fetch("/tareas.json");
  tareas.value = (await respuesta.json()).tareas;
  pendiente.value = "no";
});
</script>

<template>
  <ul data-estrategia="cliente" :data-pendiente="pendiente">
    <li v-for="tarea in tareas" :key="tarea">{{ tarea }}</li>
  </ul>
</template>

// classes/parte-7-renderizado-y-fullstack/093-las-cuatro-estrategias-de-renderizado/implementaciones/sveltekit/src/routes/cliente/+page.svelte
<script>
  import { onMount } from "svelte";

  // LA TERCERA ESTRATEGIA, ESCRITA COMO SE ESCRIBE MAL A PROPÓSITO.
  //
  // Cargar los datos en `onMount` es exactamente lo que la clase 087 verificó
  // que NO ocurre en el servidor. Así que el HTML sale con la lista vacía, y el
  // contenido aparece cuando el navegador ejecuta el JavaScript.
  //
  // En SvelteKit esto es una decisión, no un descuido: si los datos se pidieran
  // desde `load`, llegarían en el HTML. Ponerlos aquí es elegir la estrategia de
  // cliente.
  let tareas = $state([]);
  let pendiente = $state("si");

  onMount(async () => {
    const respuesta = await fetch("/tareas.json");
    tareas = (await respuesta.json()).tareas;
    pendiente = "no";
  });
</script>

<ul data-estrategia="cliente" data-pendiente={pendiente}>
  {#each tareas as tarea}
    <li>{tarea}</li>
  {/each}
</ul>
