// classes/parte-7-renderizado-y-fullstack/095-islas/implementaciones/astro/src/components/Filtro.jsx
import { useState } from "preact/hooks";

/**
 * ISLA 2: un filtro sobre la lista.
 *
 * Recibe las tareas como propiedad, así que **las tareas sí viajan**: van
 * serializadas en el atributo `props` de su `<astro-island>`. El artículo no,
 * porque no es propiedad de ninguna isla.
 *
 * Ahí está la regla que hay que llevarse: en este modelo viaja lo que cruza el
 * borde de una isla, y nada más.
 */
export default function Filtro({ tareas }) {
  const [texto, setTexto] = useState("");
  const visibles = tareas.filter((t) => t.includes(texto));
  return (
    <div data-isla="filtro">
      <input value={texto} onInput={(e) => setTexto(e.currentTarget.value)} placeholder="filtrar" />
      <ul>
        {visibles.map((t) => (
          <li key={t}>{t}</li>
        ))}
      </ul>
    </div>
  );
}

// classes/parte-7-renderizado-y-fullstack/095-islas/implementaciones/nuxt/components/Filtro.vue
<script setup lang="ts">
// ISLA 2. Recibe las tareas por propiedad, igual que en los otros dos, y por
// tanto viajan dentro de la carga útil de Nuxt.
const props = defineProps<{ tareas: string[] }>();
const texto = ref("");
const visibles = computed(() => props.tareas.filter((t) => t.includes(texto.value)));
</script>

<template>
  <div data-isla="filtro">
    <input v-model="texto" placeholder="filtrar" />
    <ul>
      <li v-for="tarea in visibles" :key="tarea">{{ tarea }}</li>
    </ul>
  </div>
</template>
