// classes/parte-7-renderizado-y-fullstack/097-carga-de-datos-junto-a-la-ruta/implementaciones/nuxt/components/Lista.vue
<script setup lang="ts">
import { anotar } from "../registro";

// EL COMPONENTE. `setup` se ejecuta al montar el componente, y al renderizar en
// el servidor eso ocurre después de que `useAsyncData` haya resuelto.
defineProps<{ tareas: { id: number; texto: string }[] }>();
anotar("render");
</script>

<template>
  <ul data-lista="tareas">
    <li v-for="tarea in tareas" :key="tarea.id" :data-tarea="tarea.id">
      <NuxtLink :to="`/tareas/${tarea.id}`">{{ tarea.texto }}</NuxtLink>
    </li>
  </ul>
</template>

// classes/parte-7-renderizado-y-fullstack/097-carga-de-datos-junto-a-la-ruta/implementaciones/sveltekit/src/lib/Lista.svelte
<script>
  import { anotar } from "./registro.js";

  // EL COMPONENTE. El bloque `<script>` de un componente de Svelte se ejecuta al
  // instanciarlo, y al renderizar en el servidor eso pasa DESPUÉS de que `load`
  // haya terminado. De ahí sale el `render` al final de la secuencia.
  let { tareas } = $props();
  anotar("render");
</script>

<ul data-lista="tareas">
  {#each tareas as tarea}
    <li data-tarea={tarea.id}>
      <a href="/tareas/{tarea.id}">{tarea.texto}</a>
    </li>
  {/each}
</ul>
