// classes/parte-7-renderizado-y-fullstack/099-la-cascada-de-peticiones/implementaciones/sveltekit/src/lib/Panel.svelte
<script>
  // La misma pantalla para las dos rutas.
  let { como, datos } = $props();
</script>

<main data-como={como}>
  <h1>Hola, {datos.usuario.nombre}</h1>
  <p data-pedidos={datos.pedidos.length}>{datos.pedidos.length} pedidos</p>
  <ul>
    {#each datos.avisos as aviso}
      <li>{aviso}</li>
    {/each}
  </ul>
</main>

// classes/parte-7-renderizado-y-fullstack/099-la-cascada-de-peticiones/implementaciones/nuxt/components/Panel.vue
<script setup lang="ts">
// La misma pantalla para las dos rutas.
defineProps<{ como: string; datos: any }>();
</script>

<template>
  <main :data-como="como">
    <h1>Hola, {{ datos.usuario.nombre }}</h1>
    <p :data-pedidos="datos.pedidos.length">{{ datos.pedidos.length }} pedidos</p>
    <ul>
      <li v-for="aviso in datos.avisos" :key="aviso">{{ aviso }}</li>
    </ul>
  </main>
</template>
