// classes/parte-7-renderizado-y-fullstack/098-acciones-de-formulario/implementaciones/sveltekit/src/routes/tareas/+page.svelte
<script>
  let { data } = $props();
</script>

<h1>Tareas</h1>
<ul>
  {#each data.tareas as tarea}
    <li data-tarea={tarea.id}>{tarea.texto}</li>
  {/each}
</ul>

<!--
  Un `<form method="POST">` sin nada más. Sin JavaScript, el navegador lo envía y
  llega a `actions.default`. Con JavaScript, se le añade `use:enhance` y
  SvelteKit lo intercepta sin recargar — y esa directiva es opcional, que es la
  forma de decir que el camino sin JavaScript es el de partida y no el de
  emergencia.
-->
<form method="POST">
  <!--
    El campo oculto declara qué se quiere hacer. En SvelteKit hay otra vía para
    lo mismo —`action="?/borrar"` elige una entrada del objeto `actions`— y es
    más limpia; el campo se deja porque el contrato es el mismo para los cinco.
  -->
  <input type="hidden" name="intencion" value="crear" />
  <input type="text" name="texto" />
  <button type="submit">Añadir</button>
</form>

<!--
  El origen de esta página, para que el contrato lo lea y lo mande de vuelta en
  la cabecera `Origin`.

  No es un adorno del ejercicio: SvelteKit rechaza con 403 cualquier POST de
  formulario cuyo `Origin` no coincida con el suyo, y lo hace **de serie, sin
  configurarlo**. Es la protección contra la falsificación de peticiones de la
  clase 080, aquí encendida por omisión. Un navegador manda esa cabecera solo; un
  `curl` sin ella, no, y por eso el contrato tiene que ponerla.
-->
<span data-origen={data.origen}></span>

// classes/parte-7-renderizado-y-fullstack/098-acciones-de-formulario/implementaciones/remix/app/routes/tareas.jsx
import { redirect } from "@remix-run/node";
import { Form, useLoaderData } from "@remix-run/react";

import { crear, listar } from "../almacen.js";

/**
 * `loader` LEE, `action` ESCRIBE, Y LAS DOS VIVEN EN EL ARCHIVO DE LA RUTA.
 *
 * La simetría no es cosmética. Como Remix conoce las dos funciones, sabe que un
 * `action` acabado invalida lo que el `loader` había traído, y **vuelve a
 * llamarlo solo**. Nadie escribe una línea para eso.
 *
 * Y el redirigir de abajo es el patrón de la clase 080 —enviar, redirigir,
 * mostrar—: sin él, recargar después de enviar reenvía el formulario.
 */
export function loader({ request }) {
  return { tareas: listar(), origen: new URL(request.url).origin };
}

export async function action({ request }) {
  const formulario = await request.formData();
  // El campo «intención» es el patrón que Remix popularizó: con varios botones
  // en el mismo formulario, es lo que distingue qué se ha pulsado. Con uno solo
  // sobra, y se deja porque el contrato es el mismo para los cinco.
  if (formulario.get("intencion") === "crear") {
    crear(formulario.get("texto"));
  }
  return redirect("/tareas");
}

export default function Tareas() {
  const { tareas, origen } = useLoaderData();
  return (
    <>
      <h1>Tareas</h1>
      <ul>
        {tareas.map((tarea) => (
          <li key={tarea.id} data-tarea={tarea.id}>
            {tarea.texto}
          </li>
        ))}
      </ul>
      {/*
        `<Form>` de Remix renderiza un `<form method="post">` de verdad. Sin
        JavaScript, el navegador lo envía él solo y llega al `action`. Con
        JavaScript, Remix intercepta el envío y hace lo mismo por detrás sin
        recargar. El mismo código, dos caminos: eso es la mejora progresiva de la
        clase 081, aquí de serie.
      */}
      <Form method="post">
        <input type="hidden" name="intencion" value="crear" />
        <input type="text" name="texto" />
        <button type="submit">Añadir</button>
      </Form>
      <span data-origen={origen}></span>
    </>
  );
}
