// classes/parte-7-renderizado-y-fullstack/097-carga-de-datos-junto-a-la-ruta/implementaciones/nuxt/components/Lista.vue
<script setup lang="ts">
import { anotar } from "../registro";

// EL COMPONENTE. `setup` se ejecuta al montar el componente, y al renderizar en
// el servidor eso ocurre después de que `useAsyncData` haya resuelto.
defineProps<{ tareas: { id: number; texto: string }[] }>();
anotar("render");
</script>

<template>
  <ul data-lista="tareas">
    <li v-for="tarea in tareas" :key="tarea.id" :data-tarea="tarea.id">
      <NuxtLink :to="`/tareas/${tarea.id}`">{{ tarea.texto }}</NuxtLink>
    </li>
  </ul>
</template>

// classes/parte-7-renderizado-y-fullstack/097-carga-de-datos-junto-a-la-ruta/implementaciones/nextjs/app/Lista.jsx
import Link from "next/link";

import { anotar } from "./registro.js";

/** EL COMPONENTE. Recibe las tareas ya cargadas y anota que se ejecuta. Ese
 *  apunte aparece siempre después de `carga:fin`. */
export default function Lista({ tareas }) {
  anotar("render");
  return (
    <ul data-lista="tareas">
      {tareas.map((tarea) => (
        <li key={tarea.id} data-tarea={tarea.id}>
          <Link href={`/tareas/${tarea.id}`}>{tarea.texto}</Link>
        </li>
      ))}
    </ul>
  );
}
